// src/client/component/App.vue
<template>
  <div class="app-container">
    <web-gl-main />
  </div>
</template>

<script>
import WegGLMain from '~/component/WebGLMain';

export default {
  name: 'app',
  components: {
    'web-gl-main': WegGLMain
  }
};
</script>

<style scoped lang="scss">
  .app-container {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
  }
</style>
<style lang="scss">
  @import "../../../node_modules/normalize.css/normalize.css";

  html, body {
    color: white;
    height: 100%;
    width: 100%;
    overflow: hidden;
  }
</style>

// src/client/component/App.jsx
import React from 'react';
import styled, { injectGlobal } from 'styled-components';
import { compose, ConnectReact } from '~/core';
import System from '~/component/System';
import Credits from '~/component/Credits';
import Modal from '~/component/Modal';
import { showModal } from '~/computed';

require('normalize.css/normalize.css');

injectGlobal`
  html, body {
    height: 100%;
    width: 100%;
    overflow: hidden;
  }
`;

const AppContainer = styled.div`
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
`;

const App = compose(
  ConnectReact(
    {
      showModal: showModal
    }
  )
)((props) => {
  return (
    <AppContainer>
      <System />
      { props.showModal && <Modal /> }
    </AppContainer>
  );
});

export default App;
